build:
	rm -Rf dist/*
	mkdir dist/stylesheets
	mkdir dist/scripts
	go generate
	GOOS=js GOARCH=wasm go build -o dist/bookcase.wasm
	cp -f /usr/lib/go/lib/wasm/wasm_exec.js dist/ 
	cp src/*.html dist/
	cp src/*.css dist/stylesheets/
	cp src/*.js dist/scripts/
	cp -Rf src/icons dist/
	cp -Rf src/screenshots dist/
	cp src/manifest.json dist/
	cp verticalpaginator/*.js dist/scripts/
	cp verticalpaginator/*.css dist/stylesheets/
	./scripts/manifest.sh
	cp src/serviceWorkers/*.js dist/
	cp dist/aozorabookcase.html dist/index.html

deploy: build
	if [[ "${AZSPADIR}x" == "x" ]]; 	then 	echo "Specify spa's root folder using the environment variable AZSPADIR"; exit 1; fi
	cp -rf dist/* ${AZSPADIR}/
	cp -f ${AZSPADIR}/aozorabookcase.html ${AZSPADIR}/index.html
	echo "done!"
